title: "The 4iAI™ Open Standard"
description: "A universal open standard for human-AI peer-to-peer symbiotic resonance and artistic integrity. Explore the Possible · Reject the Passable · Verify the Plausible · Produce the Profound via the 4iAI™ collaborative circuit · I. Inspiration (Human Catalyst) · II. Insight (Synthetic Mirror) · III. Introspection (Human Depth) · IV. Innovation (Symbiotic Resonance)."
remote_theme: just-the-docs/just-the-docs

# Enable built-in search
search_enabled: true

# Navigation settings
nav_sort: case_sensitive

# Automated XML Sitemap Generation
plugins:
  - jekyll-sitemap
