title: "The 4iAI™ Open Standard"
description: "Specification and Monograph on Artistic Integrity, Human Agency, and Peer-to-Peer Symbiotic Resonance"
remote_theme: just-the-docs/just-the-docs

# Enable built-in search
search_enabled: true

# Navigation settings
nav_sort: case_sensitive
